### PR TITLE
Add new `LARGE_FEATURE_EDGES_STRICT` ignore scheme and make it the default.

### PR DESCRIPTION
**Pull request by mfschubert**
This PR introduces a new `LARGE_FEATURE_EDGES_STRICT` ignore scheme and makes it the default. It also adds all the photonics-opt-testbed designs so they may be used in example notebooks.

The new ignore scheme is motivated by the fact that designs having "checkerboard" features (e.g. squares touching at the corner) are currently measured as having a relatively large minimum length scale. It seems more appropriate that minimum length scale of such designs should be small.

The fix is made by introducing a new way to detect edges of features. Previously, an edge pixel was any pixel removed by erosion. In the new scheme, a pixel is a solid edge pixel if
- it is bordered by three void pixels on one side (e.g. to the north, west, south, east). Explicitly, if the three void pixels are to the north, this means that the northwest, north, and northeast pixels are all void.
- it is bordered by three void pixels to the northeast, northwest, southwest, southeast. Explicitly, if the three void pixels are to the northeast, this means that they north, northeast, and east pixels are all void.

Ignored pixels in the new scheme are shown below for an example design. As the name suggests, the new scheme is stricter and so fewer pixels are ignored.
image

Additional designs with measured length scales (taken from the updated `advanced.ipynb` notebook) are below. They compare the length scales reported for the four ignore schemes.

image
image

Comparing the new scheme to the old default on the photonics-opt-testbed designs, we get the following result:
image

The new and old values largely agree, except that some designs show a small decrease in the minimum length scale. A few examples are as follows:

image
image
image

In some cases, the new scheme brings the measured length scale in line with the declared length scale.

### CODE REVIEW

**Comment by mfschubert** [comment]
@oskooi @stevengj

**Comment by oskooi** [comment]
> It also adds all the photonics-opt-testbed designs so they may be used in example notebooks.

Thanks for putting this together. Is it really necessary to duplicate all the designs from the `photonics-opt-testbed` repository in this repository just to use them in the notebooks? It might be simpler just to include the two plots above showing `large_feature_edges_strict` vs. `large_feature_edges` in the `README.md` file with a reference to those designs.

**Comment by mfschubert** [comment]
> > It also adds all the photonics-opt-testbed designs so they may be used in example notebooks.
> 
> Thanks for putting this together. Is it really necessary to duplicate all the designs from the `photonics-opt-testbed` repository in this repository just to use them in the notebooks? It might be simpler just to include the two plots above showing `large_feature_edges_strict` vs. `large_feature_edges` in the `README.md` file with a reference to those designs.

I removed the files, they were indeed not necessary. Here's a plot of the length scales for all the different schemes, plotted against the value reported by the new `large_feature_edges_strict`. I'm not sure it adds a lot of value to the readme:

image

**Comment by stevengj** [comment]
Sounds good!   Probably needs a README update, and a description (with a diagram?) outside the source code.

**Comment by mfschubert** [comment]
@stevengj @oskooi Good to go!

**Pull request merged**
